### ISSUE TITLE
Press n times to execute a command

### ISSUE THREAD

**Issue by c0zmo** [hbekel/keyman64#3]
Press n times to execute a command

Some configurations, like performing a reset, might be very annoying when issued by accident. To prevent this, I use the 'even'-policy in my configuration:
R:0 exec RESET
With this, I have to type <meta+R> twice to perform a reset. However, if I hit <meta+R> once, do some other stuff and eventually hit <meta+R> again, the reset is performed immediately (because this is how the even-policy works). My suggestion is enhancing the even/odd-policy to work like this (image a mouse double-click):

R:0 the command is issued every 2nd, 4th, 6th... time, regardless of what is typed in between
R:1 the command is issued every 1st, 3rd, 5th... time, regardless of what is typed in between
R:2 the command is issued if <meta+R> is hit two consecutive times
R:3 the command is issued if <meta+R> is hit three consecutive times
...and so on.

**Comment by hbekel** [comment]
I agree, this would be a handy feature. The counter for the key could be reset as soon as the meta key is released, so the command would only be execute when the key has been pressed the specified number of times while the meta key is held.

However, the proposed syntax is misleading, since it looks like an extension of the present mechanism (i.e. it looks like there are four commands which are executed in a cycle each time the key is pressed). There needs to be some other way to express this.

**Comment by c0zmo** [comment]
What about

R!2 exec $FA
or
R^2 exec $FA ?

**Comment by hbekel** [comment]
This feature is now implemented as a pseudo-command in the configuration file syntax:

R: requires 3 times
R: clear port a bit 0
R: sleep 10
R: tristate port a bit 0

The above reset line sequence is only executed when R is pressed three consecutive times and the meta key is not released between these key presses.

The configuration must be recreated and reflashed after upgrading the firmware since the binary configuation format has changed as well.
