### ISSUE TITLE
5V Power Connector for supplying other hardware

### ISSUE THREAD

**Issue by c0zmo** [hbekel/keyman64#5]
What do you think about a power connector where one can drive i.e. the Overlay64 without having to draw power from the motherboard? It could be placed next to the serial interface and the USB socket.

**Comment by hbekel** [comment]
Yes, that's a good idea. I'll might as well add a few while I'm at it if I find enough space.

**Comment by hbekel** [comment]
It turns out this is a bad idea after all, especially when trying to supply power and ground to the Overlay64 from the keyman64 and when also using a long cable from the mainboard keyboard connector to the keyman64. The cable will create a long ground return path which lifts the ground at the Overlay in relation to the video signal and will prevent the overlay's LM1881 from properly detecting sync, especially with dark screen contents. The overlay's GND should be connected as close as possible to the video signal output.

Thus, no other device should probably be powered from the keyman just because "it's there already".
